FROM golang:1.16-stretch as builder

ENV PKG_CONFIG_PATH /root/compiled/lib/pkgconfig

RUN apt update \
  && apt install -y wget tar build-essential pkg-config autoconf gnutls-dev git curl

RUN curl -s https://raw.githubusercontent.com/livepeer/go-livepeer/5da8ff8e521c15e5828fb9dfa619daf91a091fd0/install_ffmpeg.sh \
  | bash -

WORKDIR /root

RUN wget -qO- https://storage.googleapis.com/lp_testharness_assets/official_test_source_2s_keys_24pfs_30s_hls.tar.gz | tar xvz -C .

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -ldflags="-X 'github.com/livepeer/stream-tester/model.Version=$version' -X 'github.com/livepeer/stream-tester/model.IProduction=true'" -tags mainnet cmd/orch-tester/orch_tester.go cmd/orch-tester/broadcaster_metrics.go

FROM debian:stretch-slim

RUN apt update \
  && apt install -y ca-certificates \
  && apt clean && apt autoclean
RUN update-ca-certificates

WORKDIR /root

COPY --from=builder /root/official_test_source_2s_keys_24pfs_30s_hls official_test_source_2s_keys_24pfs_30s_hls
COPY --from=builder /root/orch_tester orch_tester

ENTRYPOINT ["/root/orch_tester"]
