name: Docker Image CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  build:
    name: Build and publish docker images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        arrays: [
          {"name": "loadtester", "file": "Dockerfile.load-tester"},
          {"name": "record-tester", "file": "Dockerfile.record-tester"},
          {"name": "orch-tester", "file": "Dockerfile.orch-tester"},
          {"name": "mist-api-connector", "file": "Dockerfile.mist-api-connector"},
          {"name": "streamtester", "file": "Dockerfile"},
        ]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            livepeer/${{ matrix.arrays.name }}
            ghcr.io/${{ github.repository }}/${{ matrix.arrays.name }}
          tags: |
            type=schedule,pattern={{date 'YYYYMMDDHHmmss'}}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha
            type=sha,format=long
            type=semver,pattern={{version}},prefix=v
            type=semver,pattern={{major}}.{{minor}},prefix=v
            type=raw,value=${{ github.event.pull_request.head.ref }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64, linux/arm64
          push: true
          build-args: |
            version=${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
          tags: ${{ steps.meta.outputs.tags }}
          file: 'docker/${{ matrix.arrays.file }}'
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Notify that new build has been uploaded
        run: curl -X POST https://holy-bread-207a.livepeer.workers.dev
