name: Docker Image CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and publish ${{ matrix.build.name }} docker images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: loadtester
            file: Dockerfile.load-tester
          - name: record-tester
            file: Dockerfile.record-tester
          - name: orch-tester
            file: Dockerfile.orch-tester
          - name: mist-api-connector
            file: Dockerfile.mist-api-connector
          - name: streamtester
            file: Dockerfile

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.CI_DOCKERHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            livepeer/${{ matrix.build.name }}
            ghcr.io/${{ github.repository }}/${{ matrix.build.name }}
          tags: |
            type=schedule,pattern={{date 'YYYYMMDDHHmmss'}}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha
            type=sha,format=long
            type=semver,pattern={{version}},prefix=v
            type=semver,pattern={{major}}.{{minor}},prefix=v
            type=raw,value=${{ github.event.pull_request.head.ref }}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          push: true
          build-args: |
            version=${{ (github.ref_type == 'tag' && github.ref_name) || (github.event.pull_request.head.sha || github.sha) }}
          tags: ${{ steps.meta.outputs.tags }}
          file: 'docker/${{ matrix.build.file }}'
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Notify that new build has been uploaded
        run: curl -X POST https://holy-bread-207a.livepeer.workers.dev
