name: Load Tester Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Registry
      env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Get git tag
      id: git_tag
      run: |
        echo ::set-output name=VERSION::$(git describe --tag --dirty)
    - name: Get build tag
      id: build_tag
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

    - name: Build the Docker image
      run: docker build . --file Dockerfile.load-tester --tag livepeer/streamtester:load-tester --build-arg version=${{ steps.git_tag.outputs.VERSION }}

    - name: Tag version
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        docker tag livepeer/streamtester:load-tester livepeer/streamtester:load-tester-${{ steps.build_tag.outputs.VERSION }}
    - name: Tag git version
      run: |
        docker tag livepeer/streamtester:load-tester livepeer/streamtester:load-tester-${{ steps.git_tag.outputs.VERSION }}
    - name: Push Docker Container to Registry
      run: |
        docker push --all-tags livepeer/streamtester
