name: Mist API Connector Docker Image CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Registry
      env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Tags
      id: tags
      uses: livepeer/action-gh-release-tags@v0
      with:
        always-latest-on-branch: mist-api-connector

    - name: Build the Docker image
      run: |
        TAGS='${{ steps.tags.outputs.tags }}'
        docker build . --file Dockerfile.mist-api-connector $(printf ' -t livepeer/mist-api-connector:%s' $TAGS) --build-arg "version=${{ steps.tags.outputs.version }}"

    - name: Push Docker Container to Registry
      run: |
        for TAG in ${{ steps.tags.outputs.tags }}; do
          docker push livepeer/mist-api-connector:$TAG
        done

    - name: Notify that new build has been uploaded
      run: curl -X POST https://holy-bread-207a.livepeer.workers.dev
