name: Orch Tester Docker Image CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Registry
      env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Tags
      id: tags
      uses: livepeer/action-gh-release-tags@v0
      with:
        always-latest-on-branch: master

    - name: Build the Docker image
      run: |
        TAGS='${{ steps.tags.outputs.tags }}'
        docker build . --file Dockerfile.orch-tester $(printf ' -t livepeer/orch-tester:%s' $TAGS) --build-arg "version=${{ steps.tags.outputs.version }}"

    - name: Push Docker Container to Registry
      run: |
        for TAG in ${{ steps.tags.outputs.tags }}; do
          docker push livepeer/orch-tester:$TAG
        done
