name: Record Tester Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Registry
      env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Tags
      id: tags
      uses: livepeer/action-gh-release-tags@v0
      with:
        tags-prefix: record-tester
        force-latest: true

    - name: Build the Docker image
      run: |
        TAGS=(${{ steps.tags.outputs.tags }})
        docker build . --file Dockerfile.record-tester ${TAGS[@]/#/--tag livepeer/streamtester:} --build-arg "version=${{ steps.tags.outputs.version }}"

    - name: Push Docker Container to Registry
      run: |
        for TAG in ${{ steps.tags.outputs.tags }}; do
          docker push livepeer/streamtester:$TAG
        done
